[package]
name = "termigotchi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde", "clock"] }
crossterm = "0.27"
directories = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
